import type { IScheduleItem } from "./model";

type SeedItem = Omit<IScheduleItem, "createdAt" | "updatedAt" | "publicado"> & {
  publicado?: boolean;
};

export const OFFICIAL_SCHEDULE: SeedItem[] = [
  {
    fecha: "2026-09-18",
    horaInicio: "08:00",
    horaFin: "09:00",
    titulo: "Desayuno",
    tipo: "comida",
    orden: 10,
    notasLogistica: "Área de comedor lista, control de asistencia inicial (Milagros). Música de fondo suave (Jesús).",
    notasCampaneros: "Control de 50 minutos. Aviso de 10 minutos para pasar al salón principal.",
  },
  {
    fecha: "2026-09-18",
    horaInicio: "09:00",
    horaFin: "09:15",
    titulo: "Instalación y Bienvenida Oficial",
    tipo: "otro",
    moderador: "P. William Acosta (@padrewilli)",
    orden: 20,
    notasLogistica:
      "Sonido principal, 2 micrófonos inalámbricos, atril con agua, proyector con logo. Agua bendita y aspersorio listos.",
    notasCampaneros: "15 minutos.",
    fichaGuion:
      "¡Muy buenos días a todos! Qué alegría ver tantos rostros que normalmente solo vemos a través de una pantalla. Bienvenidos a nuestra Primera Asamblea de Misioneros Digitales Venezuela. Estamos aquí bajo una gran premisa: ser 'Testigos de la fe en el corazón de la red', reconociendo este espacio no como una herramienta, sino como un verdadero continente donde habita la humanidad. Para poner este encuentro en las mejores manos, recibimos a Mons. Kike y al Padre William para nuestra oración y bendición inicial.",
  },
  {
    fecha: "2026-09-18",
    horaInicio: "09:15",
    horaFin: "09:45",
    titulo: "Dinámicas cristianas de integración",
    tipo: "dinamica",
    ponente: "P. Néstor López (@nestorlopez)",
    moderador: "Laura Valentina (@lauradelaureles)",
    orden: 30,
    notasLogistica: "Espacio despejado. Guitarra lista y afinada para el P. Néstor.",
    notasCampaneros: "Cronómetro de 30 minutos.",
    fichaGuion:
      "¡Hola a todos! Ya recibimos la bendición, ahora vamos a sacudirnos el viaje, salir del modo avión y a conectar nuestra propia red. Dejemos los celulares un momento. Invito a la tarima al Padre Néstor Daniel López Azuaje, sacerdote diocesano de la Arquidiócesis de Valencia, párroco de San Juan XXIII. ¡Todos de pie y listos para movernos!",
  },
  {
    fecha: "2026-09-18",
    horaInicio: "09:45",
    horaFin: "10:45",
    titulo: "Charla: La Visión del Misionero",
    tipo: "formacion",
    ponente: "P. José Juan Montalvo (Padre Borre)",
    moderador: "Laura Valentina",
    orden: 40,
    notasLogistica: "Apuntador entregado al ponente. Agua en tarima.",
    notasCampaneros: "60 minutos. A los 50 min, levantar paleta amarilla.",
    fichaGuion:
      "Comenzamos nuestro ciclo de formación. Es un honor presentarles al Padre José Juan Montalvo, mejor conocido como el Padre Borre. Él es sacerdote católico de la Arquidiócesis de Monterrey, ingeniero industrial y pionero de la pastoral digital. Fundador de 'Ilumina Más' y promotor de 'Hechos 29'. Padre, el micrófono es suyo.",
  },
  {
    fecha: "2026-09-18",
    horaInicio: "10:45",
    horaFin: "11:15",
    titulo: "Merienda",
    tipo: "comida",
    orden: 50,
    notasLogistica: "Estaciones de café (Milagros).",
    notasCampaneros: "30 minutos. Toque de campana a los 25 min.",
  },
  {
    fecha: "2026-09-18",
    horaInicio: "11:15",
    horaFin: "12:00",
    titulo: "2da Charla: Padre Borre (Continuación)",
    tipo: "formacion",
    ponente: "P. José Juan Montalvo (Padre Borre)",
    moderador: "P. Ender Moissant (@e_moissant)",
    orden: 60,
    notasLogistica: "Hidratación del ponente.",
    notasCampaneros: "45 minutos.",
    fichaGuion:
      "Retomamos nuestros asientos, hermanos. Con los motores ya calientes, continuamos profundizando con el Padre Borre en esta segunda parte de su intervención. ¡Adelante, Padre!",
  },
  {
    fecha: "2026-09-18",
    horaInicio: "12:00",
    horaFin: "13:30",
    titulo: "Almuerzo",
    tipo: "comida",
    orden: 70,
    notasCampaneros: "Control de 90 minutos.",
  },
  {
    fecha: "2026-09-18",
    horaInicio: "13:30",
    horaFin: "14:00",
    titulo: "Presentación de todos",
    tipo: "dinamica",
    moderador: "Jesús Urdaneta y Lic. Zinnia Palencia",
    orden: 80,
    notasLogistica: "Computadora conectada al video beam. Plan B: cronómetro de mano.",
    notasCampaneros: "30 minutos.",
    fichaGuion:
      "Para saber exactamente quiénes estamos aquí, vamos a ver en pantalla nuestros perfiles. A medida que aparezca su foto, levanten la mano para ubicarlos. ¡Mucha atención a las cuentas para empezar a seguirnos desde ya!",
  },
  {
    fecha: "2026-09-18",
    horaInicio: "14:00",
    horaFin: "15:00",
    titulo: "Charla: La espiritualidad en el Misionero Digital",
    tipo: "formacion",
    ponente: "P. Carlos Quiva",
    moderador: "Maria Gabriela Monis",
    orden: 90,
    notasLogistica: "Micrófono de mano probado.",
    notasCampaneros: "60 minutos. Semáforo en primera fila.",
    fichaGuion:
      "Pasar horas frente a una pantalla creando contenido puede desgastar. ¿Cómo mantenemos viva nuestra vida de oración y somos puente entre la fe y la cultura? Para responder esto, recibimos al Pbro. Carlos Quiva. Bienvenido, Padre.",
  },
  {
    fecha: "2026-09-18",
    horaInicio: "15:00",
    horaFin: "15:30",
    titulo: "Mesa de trabajo 1: Conectando nuestra red",
    tipo: "mesa",
    moderador: "Fray Juan Duque",
    orden: 100,
    notasLogistica: "Papelógrafos y marcadores distribuidos.",
    notasCampaneros: "30 minutos exactos. Toque de campana al minuto 25.",
    fichaGuion:
      "Pasamos a la acción. Cada mesa tiene un líder asignado. En los próximos 30 minutos van a presentarse rápidamente, hacer un mapa mental de sus proyectos actuales y responder: ¿Cuál es el mayor obstáculo para rezar cuando estamos conectados? Tienen hasta las 3:30. ¡Tiempo corriendo!",
  },
  {
    fecha: "2026-09-18",
    horaInicio: "15:30",
    horaFin: "16:00",
    titulo: "Refrigerio",
    tipo: "comida",
    orden: 110,
    notasCampaneros: "30 minutos.",
  },
  {
    fecha: "2026-09-18",
    horaInicio: "16:00",
    horaFin: "17:00",
    titulo: "Charla: Clausura Formativa",
    tipo: "formacion",
    ponente: "P. José Juan Montalvo (Padre Borre)",
    moderador: "P. Ender Moissant",
    orden: 120,
    notasLogistica: "Set de ponente listo. Plan B (3 sillas al frente) preparado.",
    notasCampaneros: "60 minutos.",
    fichaGuion: "Para cerrar nuestro bloque formativo de hoy, recibimos al Padre Borre quien nos guiará en este espacio.",
  },
  {
    fecha: "2026-09-18",
    horaInicio: "17:00",
    horaFin: "18:00",
    titulo: "Eucaristía",
    tipo: "liturgia",
    ponente: "P. William Acosta",
    orden: 130,
    notasLogistica: "Altar preparado, ornamentos, sonido.",
  },
  {
    fecha: "2026-09-18",
    horaInicio: "18:00",
    horaFin: "19:00",
    titulo: "Cena",
    tipo: "comida",
    orden: 140,
  },
  {
    fecha: "2026-09-18",
    horaInicio: "19:00",
    horaFin: "19:30",
    titulo: "The Chosen",
    tipo: "recreo",
    moderador: "P. William Acosta",
    ponente: "María Gabriela Moniz y P. Carlos Quiva",
    orden: 150,
    notasLogistica: "Audio formato cine, luces apagadas, proyector nítido (Jesús Urdaneta).",
    fichaGuion:
      "Para terminar la jornada, vamos a inspirarnos con buen contenido audiovisual. María Gabriela Moniz y el Padre Carlos nos introducen a 'The Chosen'.",
  },
  {
    fecha: "2026-09-18",
    horaInicio: "19:30",
    horaFin: "20:30",
    titulo: "Adoración Eucarística con invitación abierta",
    tipo: "liturgia",
    ponente: "P. Carlos Quiva",
    orden: 160,
  },
  {
    fecha: "2026-09-18",
    horaInicio: "20:30",
    horaFin: null,
    titulo: "Descanso",
    tipo: "recreo",
    orden: 170,
  },
  {
    fecha: "2026-09-19",
    horaInicio: "08:00",
    horaFin: "09:00",
    titulo: "Desayuno",
    tipo: "comida",
    orden: 10,
  },
  {
    fecha: "2026-09-19",
    horaInicio: "09:00",
    horaFin: "10:00",
    titulo: "Eucaristía",
    tipo: "liturgia",
    ponente: "Monseñor Lucio Adrián Ruiz",
    orden: 20,
  },
  {
    fecha: "2026-09-19",
    horaInicio: "10:00",
    horaFin: "10:45",
    titulo: "Charla: Retos del Jubileo",
    tipo: "formacion",
    ponente: "Mons. Lucio Adrián Ruiz",
    moderador: "José Ángel, Seminarista",
    orden: 30,
    notasLogistica: "Presentación lista. Silla cómoda.",
    notasCampaneros: "45 minutos. Paletas preventivas.",
    fichaGuion:
      "Buenos días, familia. Hoy vamos a mirar hacia el futuro. El Jubileo nos plantea retos inmensos. Para hablar de nuestro papel allí, recibimos a Monseñor Lucio Adrián Ruiz, Secretario del Dicasterio para la Comunicación del Vaticano y Secretario del Dicasterio para el Servicio de la Caridad. ¡Bienvenido, Monseñor!",
  },
  {
    fecha: "2026-09-19",
    horaInicio: "10:45",
    horaFin: "11:00",
    titulo: "Refrigerio",
    tipo: "comida",
    orden: 40,
    notasCampaneros: "15 minutos (ajustado para conectar directo).",
  },
  {
    fecha: "2026-09-19",
    horaInicio: "11:00",
    horaFin: "12:00",
    titulo: "Taller práctico / Masterclass: El poder de una foto y un video",
    tipo: "formacion",
    ponente: "Luis Machado",
    moderador: "Fray Juan Duque",
    descripcion: "Técnicas ágiles de edición para Reels, diseño de flyers y prompts de IA.",
    orden: 50,
    notasLogistica: "Adaptador para proyectar pantalla de celular/tablet. Internet estable.",
    notasCampaneros: "60 minutos.",
    fichaGuion:
      "Entramos al taller técnico de esta mañana. Recibimos a Luis Machado, Director Audiovisual y Filmmaker: 'EL PODER DE UNA FOTO Y UN VIDEO PARA CONTAR UNA HISTORIA'. ¡A sacar donde anotar!",
  },
  {
    fecha: "2026-09-19",
    horaInicio: "12:00",
    horaFin: "13:30",
    titulo: "Almuerzo",
    tipo: "comida",
    orden: 60,
    notasCampaneros: "90 minutos.",
  },
  {
    fecha: "2026-09-19",
    horaInicio: "13:30",
    horaFin: "14:30",
    titulo: "Charla: Pastoral digital",
    tipo: "formacion",
    ponente: "P. José Juan Montalvo (Padre Borre)",
    moderador: "P. Néstor López",
    orden: 70,
    notasLogistica: "Presentación lista, sonido ajustado.",
    notasCampaneros: "60 minutos.",
    fichaGuion:
      "Familia, regresamos de almorzar con las baterías al 100%. Evangelizar en el ecosistema digital exige salir al encuentro de las periferias. Recibimos nuevamente al Padre Borre, quien nos hablará a fondo sobre la verdadera Pastoral Digital.",
  },
  {
    fecha: "2026-09-19",
    horaInicio: "14:30",
    horaFin: "15:30",
    titulo: "Panel de Expertos",
    tipo: "panel",
    ponente: "P. Borre, Mons. Lucio y panelistas por designar",
    moderador: "P. William Acosta",
    orden: 80,
    notasLogistica: "3-4 sillas en semicírculo, micrófonos, hojas Análisis FODA.",
    notasCampaneros: "60 minutos (30 debate + 30 mesas).",
    fichaGuion:
      "Invitamos a nuestros panelistas a subir. Tendremos 30 minutos de debate sobre cómo aplicar la pastoral digital. Luego, pasaremos a las mesas para diseñar un Plan de Acción concreto de 3 pasos para nuestras comunidades.",
  },
  {
    fecha: "2026-09-19",
    horaInicio: "15:30",
    horaFin: "16:30",
    titulo: "Refrigerio",
    tipo: "comida",
    orden: 90,
    notasCampaneros: "60 minutos (descanso largo).",
  },
  {
    fecha: "2026-09-19",
    horaInicio: "16:30",
    horaFin: "17:30",
    titulo: "Líneas guías",
    tipo: "formacion",
    ponente: "Mons. Lucio Adrián Ruiz",
    moderador: "Laura Valentina",
    orden: 100,
    notasLogistica: "Apuntador láser y proyector.",
    notasCampaneros: "60 minutos.",
    fichaGuion:
      "Luego de un debate tan nutritivo, necesitamos estructurar nuestros próximos pasos como Iglesia local. Para presentarnos las líneas guías de acción, recibimos nuevamente a Monseñor Lucio.",
  },
  {
    fecha: "2026-09-19",
    horaInicio: "17:30",
    horaFin: "18:00",
    titulo: "Mesa de trabajo 3: Laboratorio de Creación",
    tipo: "mesa",
    moderador: "Milagros de los Santos",
    orden: 110,
    notasLogistica: "Hojas con reto impreso y cronómetros. Apoyo técnico: Fray Juan Duque.",
    notasCampaneros: "60 minutos exactos. Proyección de reloj en pantalla.",
    fichaGuion:
      "Llegó el momento del reto técnico. Tendrán 60 minutos para estructurar un prompt maestro que genere guiones para voice-over o cápsula de audio de un minuto. Los temas centrales están en sus mesas. ¡A crear!",
  },
  {
    fecha: "2026-09-19",
    horaInicio: "18:00",
    horaFin: "19:00",
    titulo: "Cena",
    tipo: "comida",
    orden: 120,
  },
  {
    fecha: "2026-09-19",
    horaInicio: "19:00",
    horaFin: "20:45",
    titulo: "Oración y concierto-animación",
    tipo: "recreo",
    ponente: "Milagros (ARCA) / Opción B: P. Néstor López y Jesús Urdaneta",
    orden: 130,
    notasLogistica: "Sonido ajustado para música en vivo, luces dinámicas.",
  },
  {
    fecha: "2026-09-19",
    horaInicio: "20:45",
    horaFin: null,
    titulo: "Descanso",
    tipo: "recreo",
    orden: 140,
  },
  {
    fecha: "2026-09-20",
    horaInicio: "08:00",
    horaFin: "09:00",
    titulo: "Desayuno",
    tipo: "comida",
    orden: 10,
  },
  {
    fecha: "2026-09-20",
    horaInicio: "09:00",
    horaFin: "10:00",
    titulo: "Masterclass de cierre: El arte de acompañar en lo digital",
    tipo: "formacion",
    ponente: "Milagros de los Santos",
    moderador: "P. Ender Moissant",
    orden: 20,
    notasLogistica: "Proyector, micrófono central.",
    notasCampaneros: "60 minutos.",
    fichaGuion:
      "Comenzamos nuestro último día. Masterclass conclusiva: 'El arte de acompañar en lo digital y estilos que transforman', a cargo de Milagros de los Santos.",
  },
  {
    fecha: "2026-09-20",
    horaInicio: "10:00",
    horaFin: "10:30",
    titulo: "Mesa de trabajo 4: Redes echadas al mar",
    tipo: "mesa",
    moderador: "Maylu Burelli",
    orden: 30,
    notasLogistica: "Tarjetas de cartulina y bolígrafos.",
    notasCampaneros: "30 minutos. Campana a los 25 min (José Ángel).",
    fichaGuion:
      "Última reunión de equipos. Tienen 30 minutos para resumir esta asamblea en una sola frase y escribir en la tarjeta su compromiso personal de acción.",
  },
  {
    fecha: "2026-09-20",
    horaInicio: "10:30",
    horaFin: "11:00",
    titulo: "Agradecimientos y plenaria final",
    tipo: "otro",
    moderador: "P. William Acosta",
    orden: 40,
    notasLogistica: "Micrófono rotativo en el salón.",
    notasCampaneros: "30 minutos.",
    fichaGuion:
      "Vamos a escuchar la frase conclusiva de cada mesa. Hoy hemos dado un paso inmenso para consolidar la Red Nacional de Misioneros Digitales de Venezuela.",
  },
  {
    fecha: "2026-09-20",
    horaInicio: "11:00",
    horaFin: null,
    titulo: "Eucaristía de clausura y despedida",
    tipo: "liturgia",
    ponente: "P. José Juan Montalvo (Padre Borre)",
    orden: 50,
    notasLogistica: "Preparación solemne. Fotografía oficial del grupo al finalizar (Jesús Urdaneta).",
  },
];
